spring:
  # Security OAuth
  security:
    oauth2.client:
      registration:
        kakao:
          client-name: kakao
          client-id: {CLIENT_ID}
          client-secret: {CLIENT_SECRET}
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          authorization-grant-type: authorization_code
          client-authentication-method: POST
          scope:
            - profile_nickname
            - account_email
        naver:
          client-name: naver
          client-id: {CLIENT_ID}
          client-secret: {CLIENT_SECRET}
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          authorization-grant-type: authorization_code
          scope:
            - name
            - email
      # Provider 설정
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          user-info-uri: https://kapi.kakao.com/v2/user/me
          token-uri: https://kauth.kakao.com/oauth/token
          user-name-attribute: id
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          user-info-uri: https://openapi.naver.com/v1/nid/me
          token-uri: https://nid.naver.com/oauth2.0/token
          user-name-attribute: response

#Jwt Secret Key
jwt:
  secretKey: {SECRET_KEY}