spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nearbuy?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      #username: root
      #password:
      uri: mongodb://localhost:27017/nearbuy
      #authentication-database: admin
